### PR TITLE
Creating Hmac now supports accented characters

### PR DESCRIPTION
**Pull request by lindehoff**
This fixes the problem describe over here https://github.com/mariusc23/deployer/issues/1

### CODE REVIEW

**Comment by mariusc23** [comment]
Looks good, thanks!

**Comment by lindehoff** [comment]
No problem, I really like your deployer.

**Comment by mariusc23** [comment]
Aw, glad to hear that! I'm curious, how did you find out about it?

**Comment by lindehoff** [comment]
Google search for nodejs `webhocks X-Hub-Signature`.
I first looked at https://github.com/luismatute/Webhook_Example but it lacked the support for `X-Hub-Signature` and harder to set up. Then I found your solution which where more elegant.

**Pull request merged**
